import { useState } from "react";
import { useNavigate } from "react-router-dom";

const languages = ["Java", "Python", "C++", "JavaScript"];
const submissionTypes = ["Review", "Optimize", "Both"];

export default function Submit() {
  const [language, setLanguage] = useState("Java");
  const [code, setCode] = useState("");
  const [submissionType, setSubmissionType] = useState("Review");
  const [analyzing, setAnalyzing] = useState(false);

  const navigate = useNavigate(); // ✅ REQUIRED

  const handleAnalyze = () => {
    if (!code.trim()) return;

    setAnalyzing(true);

    // Simulate API call
    setTimeout(() => {
      setAnalyzing(false);

      navigate("/result", {
        state: {
          language,
          submissionDate: new Date().toLocaleDateString(),
          qualityScore: 82,
          improvementPercent: 34,
          timeComplexity: "O(n log n)",
          spaceComplexity: "O(n)",
          originalCode: code,
          optimizedCode:
            "// Optimized version generated by AI\n// Example improvement applied",
          issues: [
            {
              type: "Performance",
              description:
                "Nested loop can be optimized to reduce unnecessary comparisons.",
            },
            {
              type: "Maintainability",
              description:
                "Consider adding documentation and meaningful variable names.",
            },
          ],
        },
      });
    }, 1500);
  };

  return (
    <div className="min-h-screen bg-gray-950 text-gray-100 px-4 py-10 flex justify-center">
      <div className="w-full max-w-3xl flex flex-col gap-8">
        {/* Header */}
        <div className="flex flex-col gap-1">
          <h1 className="text-2xl font-bold tracking-tight text-gray-50">
            Submit Code for AI Review
          </h1>
          <p className="text-sm text-gray-500">
            Paste your code below and let our AI engine analyze and optimize it.
          </p>
        </div>

        {/* Main Card */}
        <div className="rounded-xl border border-gray-800 bg-gray-900 p-6 flex flex-col gap-6">
          {/* Language Selector */}
          <div className="flex flex-col gap-2">
            <label className="text-sm font-medium text-gray-300">
              Language
            </label>
            <select
              value={language}
              onChange={(e) => setLanguage(e.target.value)}
              className="w-full max-w-xs rounded-lg border border-gray-700 bg-gray-800 px-3 py-2 text-sm text-gray-100 outline-none focus:border-emerald-500 focus:ring-1 focus:ring-emerald-500"
            >
              {languages.map((lang) => (
                <option key={lang}>{lang}</option>
              ))}
            </select>
          </div>

          {/* Code Editor */}
          <div className="flex flex-col gap-2">
            <label className="text-sm font-medium text-gray-300">
              Your Code
            </label>
            <textarea
              value={code}
              onChange={(e) => setCode(e.target.value)}
              placeholder={`// Paste your ${language} code here...`}
              rows={14}
              spellCheck={false}
              className="w-full rounded-lg border border-gray-700 bg-gray-950 px-4 py-3 font-mono text-sm text-gray-100 placeholder-gray-600 outline-none resize-y focus:border-emerald-500 focus:ring-1 focus:ring-emerald-500"
            />
          </div>

          {/* Submission Type Toggle */}
          <div className="flex flex-col gap-2">
            <span className="text-sm font-medium text-gray-300">
              Submission Type
            </span>
            <div className="flex gap-2">
              {submissionTypes.map((type) => {
                const isActive = submissionType === type;
                return (
                  <button
                    key={type}
                    onClick={() => setSubmissionType(type)}
                    className={`px-4 py-2 rounded-lg text-sm font-medium transition-colors ${
                      isActive
                        ? "bg-emerald-500/15 text-emerald-400 border border-emerald-500/40"
                        : "bg-gray-800 text-gray-400 border border-gray-700 hover:text-gray-200 hover:border-gray-600"
                    }`}
                  >
                    {type}
                  </button>
                );
              })}
            </div>
          </div>

          {/* Analyze Button */}
          <button
            onClick={handleAnalyze}
            disabled={analyzing || !code.trim()}
            className={`w-full flex items-center justify-center gap-2 rounded-lg px-5 py-3 text-sm font-semibold transition-colors ${
              analyzing || !code.trim()
                ? "bg-emerald-500/20 text-emerald-400/50 cursor-not-allowed"
                : "bg-emerald-500 text-gray-950 hover:bg-emerald-400"
            }`}
          >
            {analyzing ? "Analyzing..." : "Analyze & Optimize"}
          </button>
        </div>
      </div>
    </div>
  );
}
